---
# Manually install collections using the following command:
#   cd collections; ansible-galaxy collection install -r requirements.yml -p ./ -f
# More info can be found here: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

collections:

    # Ansible Community General Collection
    # This collection has a few dependencies that will result in downloading other collections
    # https://github.com/ansible-collections/community.general
    - name: community.general

    # https://github.com/ansible-collections/azure
    - name: azure.azcollection

    # https://github.com/ansible-collections/vmware
    - name: community.vmware

    # https://github.com/ansible-collections/amazon.aws
    - name: amazon.aws

    # https://github.com/ansible-collections/google.cloud
    - name: google.cloud