# Convert INI inventory format using this command:
# ansible-inventory -i inventory --list --export --yaml > inventory.yml

all:
  children:
    aws: {}
    azure: {}
    ungrouped: {}
    vmware:
      children:
        vmware_test:
          children:
            imperva:
              children:
                linux:
                  hosts:
                    dummy.linux.host: {}
                windows:
                  hosts:
                    dummy.windows.host: {}
